# Generated by Django 5.1.3 on 2024-12-02 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('tenantapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, help_text='The address of the user.', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='The phone number of the user.', max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='tenant',
            field=models.ForeignKey(default=1, help_text='The tenant this user belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='users', to='adminapp.tenant'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, help_text='The full name of the user.', max_length=100, null=True),
        ),
    ]
